use project;

CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);


-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT COUNT(*) FROM supplier;
SELECT COUNT(*) FROM categories;
SELECT COUNT(*) FROM employees;
SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM products;
SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM order_details;

SELECT * 
FROM products 
WHERE sup_id NOT IN (SELECT sup_id FROM supplier)
   OR cat_id NOT IN (SELECT cat_id FROM categories);

SELECT * 
FROM orders 
WHERE cust_id NOT IN (SELECT cust_id FROM customers)
   OR emp_id NOT IN (SELECT emp_id FROM employees);

-- 1. Customer Insights
-- unique customers who placed orders
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

-- 2. Customers with highest number of orders
SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id
ORDER BY total_orders DESC;


-- 3. Total & average purchase value per customer
SELECT c.cust_id, c.cust_name,
       SUM(od.total_price) AS total_purchase,
       AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id;

-- 4. Top 5 customers by total purchase
SELECT c.cust_name, SUM(od.total_price) AS total_spent
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id
ORDER BY total_spent DESC
LIMIT 5;

-- 2. Product Performance
-- 1. Products count per category
SELECT cat.cat_name, COUNT(p.prod_id) AS product_count
FROM categories cat
LEFT JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_id;


-- 2. Average price per category
SELECT cat.cat_name, AVG(p.price) AS avg_price
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_id;

-- 3. Top products by sales volume
SELECT p.prod_name, SUM(od.quantity) AS total_qty
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id
ORDER BY total_qty DESC;

-- 4. Total revenue generated by each product
SELECT p.prod_name, SUM(od.total_price) AS revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id
ORDER BY revenue DESC;

-- 5. Sales variation by category & supplier
SELECT cat.cat_name, s.sup_name,
       SUM(od.total_price) AS total_revenue
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories cat ON p.cat_id = cat.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY cat.cat_id, s.sup_id;

-- 3. Sales & Order Trends
-- 1. Total orders
SELECT COUNT(*) AS total_orders FROM orders;

-- 2. Average order value
SELECT AVG(t.order_total) AS avg_order_value
FROM (
    SELECT o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) t;

-- 3. Dates with most orders
SELECT order_date, COUNT(*) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;

-- 4. Monthly order & revenue trends
SELECT DATE_FORMAT(order_date, '%Y-%m') AS month,
       COUNT(*) AS order_count,
       SUM(od.total_price) AS revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;

-- 5. Weekday vs Weekend patterns
SELECT 
    DAYNAME(order_date) AS day,
    COUNT(o.ord_id) AS order_count
FROM orders o
GROUP BY day
ORDER BY order_count DESC;

-- 4. Supplier Contribution
-- 1 Number of suppliers
SELECT COUNT(*) AS total_suppliers FROM supplier;

-- 2. Supplier with most products
SELECT s.sup_name, COUNT(p.prod_id) AS product_count
FROM supplier s
LEFT JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id
ORDER BY product_count DESC;

-- 3. Average price of products per supplier
SELECT s.sup_name, AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id;

-- 4. Supplier revenue contribution
SELECT s.sup_name, SUM(od.total_price) AS total_revenue
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY s.sup_id
ORDER BY total_revenue DESC;

-- 5. Employee Performance
-- 1. Employees who processed orders
SELECT COUNT(DISTINCT emp_id) AS active_employees
FROM orders;

-- 2. Employee with most orders
SELECT e.emp_name, COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id
ORDER BY total_orders DESC;

-- 3. Total sales handled by each employee
SELECT e.emp_name, SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id;

-- 4. Average order value per employee
SELECT e.emp_name, AVG(t.order_total) AS avg_order_value
FROM (
    SELECT o.emp_id, o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) t
JOIN employees e ON t.emp_id = e.emp_id
GROUP BY e.emp_id;

-- 6. Order Details Deep Dive
-- 1. Relationship between quantity & total price
SELECT quantity, total_price
FROM order_details
ORDER BY quantity;

-- 2. Average quantity ordered per product
SELECT p.prod_name, AVG(od.quantity) AS avg_qty
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id;

-- 3. Unit price variation across orders
SELECT p.prod_name, od.each_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
ORDER BY p.prod_id;

select * from order_details;






































